spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: oracle
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost/xe
    username: doc_table
    password: doc_table
  servlet:
    multipart:
      max-file-size: 3MB
#logging:
#  level:
#    org.hibernate.SQL: debug

#    org.hibernate.type: trace

table-create:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost/xe
  username: doc_table
  password: doc_table
