spring:
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    database: oracle
  #    properties:ß
#      hibernate:
#        format_sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost/xe
    username: doc_table
    password: doc_table


  #    driver-class-name: com.tmax.tibero.jdbc.TbDriver
#    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
#    username: gmdmi
#    password: gmdmi
  servlet:
    multipart:
      max-file-size: 3MB
#logging:\
#  level:
#    org.hibernate.SQL: debug

#    org.hibernate.type: trace

table-create:
#  driver-class-name: oracle.jdbc.driver.OracleDriver
#  url: jdbc:oracle:thin:@10.47.39.124:1521/orcl
#  username: erdbd00
#  password: erdbd00
  driver-class-name: com.tmax.tibero.jdbc.TbDriver
##  url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
  url: jdbc:tibero:thin:@localhost:8629:tibero
  username: gmdmi
  password: gmdmi
